import json
import os
import matplotlib.pyplot as plt
import numpy as np
from data_generator import euclidean_distance

def get_node_coordinates(customers, node_id, depot):
    """Retrieves (x, y) coordinates for a given node ID (0 for depot, >0 for customer)."""
    if node_id == 0:
        return depot['x'], depot['y']
    
    # Note: Customers data is a list of dicts in this utility
    for customer in customers:
        if customer['id'] == node_id:
            return customer['x'], customer['y']
    raise ValueError(f"Node ID {node_id} not found in customer list.")

def visualize_strategy(instance, strategy, output_dir):
    """
    Plots the planned routes (strategy) generated by the deterministic solver.
    
    Args:
        instance (dict): The loaded instance data (with customers as list of dicts).
        strategy (dict): The solved strategy data (routes).
        output_dir (str): The directory to save the visualization PNG file.
    """
    
    routes = strategy.get('routes', [])
    num_vehicles = instance.get('num_vehicles', 0)
    
    plt.figure(figsize=(12, 12))
    plt.title(f"ORTools Deterministic Strategy: {strategy['instance_file']} | Dist: {strategy['total_distance']:.0f} mi", fontsize=14)
    plt.xlabel("X Coordinate")
    plt.ylabel("Y Coordinate")
    
    colors = plt.cm.gist_rainbow(np.linspace(0, 1, num_vehicles))
    
    # 1. Plot Depot and Customers
    depot_x, depot_y = instance['depot']['x'], instance['depot']['y']
    plt.scatter(depot_x, depot_y, marker='s', color='black', s=500, label='Depot', zorder=5)
    
    customer_coords = [(c['x'], c['y']) for c in instance['customers']]
    demands = [c['demand'] for c in instance['customers']]
    plt.scatter([c[0] for c in customer_coords], [c[1] for c in customer_coords], 
                c='gray', s=np.array(demands) * 3, alpha=0.6, label='Customers', zorder=3)

    # 2. Plot Routes
    for v, route in enumerate(routes):
        if not route: continue

        route_coords_x = []
        route_coords_y = []
        
        for step in route:
            x, y = get_node_coordinates(instance['customers'], step['node_id'], instance['depot'])
            route_coords_x.append(x)
            route_coords_y.append(y)
        
        # Plot path (line)
        plt.plot(route_coords_x, route_coords_y, 
                 color=colors[v % num_vehicles], 
                 linestyle='-', 
                 linewidth=2.5, 
                 alpha=0.7, 
                 label=f'Vehicle {v+1}')
        
        # Plot step points (Excluding start/end depot points)
        if len(route_coords_x) > 2:
            plt.scatter(route_coords_x[1:-1], route_coords_y[1:-1], 
                        marker='o', 
                        color=colors[v % num_vehicles], 
                        s=50, 
                        zorder=4)

    # Final adjustments
    plt.xlim(0, 100)
    plt.ylim(0, 100)
    plt.legend(loc='upper right')
    plt.grid(True, linestyle='--', alpha=0.4)
    plt.gca().set_aspect('equal', adjustable='box')
    
    # 3. Save Visualization
    base_filename = os.path.basename(strategy['instance_file']).replace('.json', '')
    output_filename = f"{base_filename}_deterministic_strategy.png"
    output_filepath = os.path.join(output_dir, output_filename)
    
    plt.savefig(output_filepath)
    plt.close()
    print(f"  -> Saved visual: {output_filename}")