"""HTTP server for the live web UI.

Run with: ``python -m webui.app [--port 8765]``

Routes:
  GET  /                  -> templates/index.html
  GET  /status            -> JSON snapshot of EventBus state
  GET  /snapshots/<path>  -> serve PNG from static/snapshots/
  GET  /static/<path>     -> serve static assets
  POST /log               -> body=plain text, append lines to log buffer
  POST /reset             -> clear the bus (no auth -- localhost only)

ThreadingHTTPServer so multiple browsers + the bench harness can talk
to it concurrently. No auth, no TLS -- bind to 127.0.0.1.
"""
from __future__ import annotations

import argparse
import json
import logging
import mimetypes
import os
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

from webui.event_bus import bus, reset as reset_bus
from webui.processes import registry, set_server_url, validate_args, WHITELIST

_LOG = logging.getLogger("webui.app")
_HERE = Path(__file__).resolve().parent
_TEMPLATE_INDEX = _HERE / "templates" / "index.html"
_TEMPLATE_VIEWER = _HERE / "templates" / "viewer.html"
_STATIC_ROOT = _HERE / "static"
_SNAPSHOT_ROOT = _STATIC_ROOT / "snapshots"
# SPEC-WEBUI-06 -- publish HTML progress reports off the page.
# Resolves to <repo>/WorldsFinestVRP/Progress_Report.html (the canonical
# rendered report; regenerated by bench/scripts/build_progress_report.py
# when that script exists).
_REPO_ROOT = _HERE.parent
_PROGRESS_REPORT_HTML = _REPO_ROOT / "WorldsFinestVRP" / "Progress_Report.html"


class WebUIHandler(BaseHTTPRequestHandler):
    server_version = "WorldsFinestVRP-WebUI/0.1"

    def log_message(self, fmt: str, *args: Any) -> None:
        # Quiet -- web access is logged via /log POSTs from solvers.
        return

    def do_OPTIONS(self) -> None:  # noqa: N802
        # CORS preflight -- accept anything, the server is bound to 127.0.0.1 only.
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.send_header("Content-Length", "0")
        self.end_headers()

    def do_GET(self) -> None:  # noqa: N802
        path = self.path.split("?", 1)[0]
        if path in ("/", "/index.html"):
            self._serve_file(_TEMPLATE_INDEX, "text/html; charset=utf-8")
        elif path == "/viewer":
            self._serve_file(_TEMPLATE_VIEWER, "text/html; charset=utf-8")
        elif path == "/control/list":
            self._serve_json({"procs": registry().list()})
        elif path == "/status":
            self._serve_json(bus().snapshot())
        elif path.startswith("/snapshots/"):
            rel = path[len("/snapshots/"):].lstrip("/")
            self._serve_static(_SNAPSHOT_ROOT / rel)
        elif path.startswith("/static/"):
            rel = path[len("/static/"):].lstrip("/")
            self._serve_static(_STATIC_ROOT / rel)
        elif path == "/reports/progress":
            # SPEC-WEBUI-06 -- canonical Progress_Report.html
            if _PROGRESS_REPORT_HTML.exists():
                self._serve_file(_PROGRESS_REPORT_HTML, "text/html; charset=utf-8")
            else:
                self._send_status(
                    404,
                    b"Progress report not found at WorldsFinestVRP/Progress_Report.html",
                )
        elif path == "/reports":
            # tiny index listing the reports we know about
            body = (
                b"<!doctype html><html><head><title>reports</title></head>"
                b"<body style='font-family:monospace;background:#0f1115;color:#e6e9ef;padding:18px'>"
                b"<h2>WorldsFinestVRP reports</h2><ul>"
                b"<li><a style='color:#60a5fa' href='/reports/progress'>"
                b"Progress_Report.html</a> &mdash; the canonical rendered report</li>"
                b"</ul></body></html>"
            )
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        else:
            self._send_status(404, b"not found")


    def do_POST(self) -> None:  # noqa: N802
        path = self.path.split("?", 1)[0]
        n = int(self.headers.get("Content-Length", "0"))
        body = self.rfile.read(n) if n else b""
        if path == "/log":
            text = body.decode("utf-8", errors="replace")
            for line in text.splitlines():
                bus().add_log(line)
            self._serve_json({"ok": True})
        elif path == "/reset":
            reset_bus()
            self._serve_json({"ok": True})
        elif path == "/event":
            self._dispatch_event(body)
        elif path == "/control/run":
            self._control_run(body)
        elif path == "/control/stop":
            self._control_stop(body)
        elif path == "/control/clear-snapshots":
            self._control_clear_snapshots()
        elif path == "/control/build-report":
            self._control_build_report()
        else:
            self._send_status(404, b"not found")

    # ---- /control/* implementations -----------------------------

    def _control_run(self, body: bytes) -> None:
        try:
            data = json.loads(body or b"{}")
            script = str(data.get("script", ""))
            args = list(data.get("args", []) or [])
        except Exception as e:
            self._send_status(400, f"bad json: {e}".encode("utf-8"))
            return
        if script not in WHITELIST:
            self._send_status(400, f"unknown script: {script}".encode("utf-8"))
            return
        try:
            # Validate first so we return a clean 400 on bad args.
            validate_args(script, args)
        except ValueError as e:
            self._send_status(400, str(e).encode("utf-8"))
            return
        try:
            info = registry().run(script, args)
        except RuntimeError as e:
            # Already running.
            self._send_json_with_code(409, {"ok": False, "error": str(e)})
            return
        except ValueError as e:
            self._send_status(400, str(e).encode("utf-8"))
            return
        except Exception as e:
            self._send_status(500, f"spawn failed: {e}".encode("utf-8"))
            return
        self._serve_json({"ok": True, **info})

    def _control_stop(self, body: bytes) -> None:
        try:
            data = json.loads(body or b"{}")
            name = str(data.get("name", ""))
        except Exception as e:
            self._send_status(400, f"bad json: {e}".encode("utf-8"))
            return
        if not name:
            self._send_status(400, b"missing 'name'")
            return
        try:
            info = registry().stop(name)
        except Exception as e:
            self._send_status(500, f"stop failed: {e}".encode("utf-8"))
            return
        self._serve_json({"ok": True, **info})

    def _control_clear_snapshots(self) -> None:
        # Hard-isolate: glob ONLY *.png under _SNAPSHOT_ROOT, never recurse,
        # never rmtree. Resolve each path and reject anything outside.
        removed = 0
        snap_root = _SNAPSHOT_ROOT.resolve()
        try:
            snap_root.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            self._send_status(500, f"mkdir failed: {e}".encode("utf-8"))
            return
        for png in _SNAPSHOT_ROOT.glob("*.png"):
            try:
                resolved = png.resolve()
                resolved.relative_to(snap_root)
            except (ValueError, OSError):
                continue
            try:
                resolved.unlink()
                removed += 1
            except OSError:
                pass
        self._serve_json({"ok": True, "removed": removed})

    def _control_build_report(self) -> None:
        # TODO(SPEC-WEBUI-06): when bench/scripts/build_progress_report.py
        # exists, subprocess it here. For now, just touch the existing
        # Progress_Report.html so the front-end can detect a re-publish.
        try:
            _PROGRESS_REPORT_HTML.parent.mkdir(parents=True, exist_ok=True)
            if not _PROGRESS_REPORT_HTML.exists():
                _PROGRESS_REPORT_HTML.write_text(
                    "<!doctype html><html><body>"
                    "<h2>WorldsFinestVRP progress report</h2>"
                    "<p>(placeholder; build_progress_report.py will populate)</p>"
                    "</body></html>",
                    encoding="utf-8",
                )
            else:
                # Touch mtime so clients can detect re-publish.
                now = time.time()
                os.utime(_PROGRESS_REPORT_HTML, (now, now))
        except Exception as e:
            self._send_status(500, f"build_report failed: {e}".encode("utf-8"))
            return
        self._serve_json({"ok": True, "report_url": "/reports/progress"})

    def _send_json_with_code(self, code: int, obj: dict[str, Any]) -> None:
        data = json.dumps(obj).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def _dispatch_event(self, body: bytes) -> None:
        """POST /event {type: 'stage'|'snapshot'|'progress'|'judges', payload: {...}}"""
        try:
            data = json.loads(body or b"{}")
            etype = str(data.get("type", ""))
            payload = data.get("payload", {}) or {}
        except Exception as e:
            self._send_status(400, f"bad json: {e}".encode("utf-8"))
            return
        b = bus()
        try:
            if etype == "stage":
                b.set_stage(str(payload.get("stage", "")),
                            str(payload.get("msg", "")),
                            **{k: v for k, v in payload.items()
                                if k not in ("stage", "msg")})
            elif etype == "snapshot":
                b.add_snapshot(label=str(payload["label"]),
                               rel_path=str(payload["rel_path"]),
                               stream=str(payload.get("stream", "default")),
                               **{k: v for k, v in payload.items()
                                  if k not in ("label", "rel_path", "stream")})
            elif etype == "progress":
                b.set_bench_progress(name=str(payload["name"]),
                                     completed=int(payload["completed"]),
                                     total=int(payload["total"]),
                                     eta_seconds=payload.get("eta_seconds"))
            elif etype == "judges":
                b.set_judge_panel(pair_id=str(payload["pair_id"]),
                                  judges=list(payload.get("judges", [])),
                                  consensus=payload.get("consensus"))
            elif etype == "log":
                b.add_log(str(payload.get("line", "")))
            elif etype == "agent":
                b.set_agent_status(
                    name=str(payload["name"]),
                    status=str(payload.get("status", "")),
                    progress=payload.get("progress"),
                    eta_seconds=payload.get("eta_seconds"),
                    summary=str(payload.get("summary", "")),
                    **{k: v for k, v in payload.items()
                        if k not in ("name", "status", "progress",
                                     "eta_seconds", "summary")},
                )
            elif etype == "series":
                b.push_series_point(
                    stream=str(payload["stream"]),
                    x=float(payload["x"]), y=float(payload["y"]),
                )
            else:
                self._send_status(400, f"unknown type: {etype}".encode("utf-8"))
                return
            self._serve_json({"ok": True})
        except KeyError as e:
            self._send_status(400, f"missing field: {e}".encode("utf-8"))
        except Exception as e:
            self._send_status(500, f"dispatch error: {e}".encode("utf-8"))

    # ---- helpers ---------------------------------------------------

    def _send_status(self, code: int, body: bytes = b"") -> None:
        self.send_response(code)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if body:
            self.wfile.write(body)


    def _serve_file(self, path: Path, ctype: str) -> None:
        if not path.exists():
            self._send_status(404, b"missing")
            return
        data = path.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", ctype)
        self.send_header("Cache-Control", "no-store")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def _serve_static(self, path: Path) -> None:
        # Hard-isolate: refuse anything escaping the static root.
        try:
            resolved = path.resolve()
            resolved.relative_to(_STATIC_ROOT.resolve())
        except (ValueError, OSError):
            self._send_status(403)
            return
        if not resolved.is_file():
            self._send_status(404)
            return
        ctype, _ = mimetypes.guess_type(str(resolved))
        self._serve_file(resolved, ctype or "application/octet-stream")


    def _serve_json(self, obj: dict[str, Any]) -> None:
        data = json.dumps(obj).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)


def serve(port: int = 8765, host: str = "127.0.0.1") -> None:
    _SNAPSHOT_ROOT.mkdir(parents=True, exist_ok=True)
    server = ThreadingHTTPServer((host, port), WebUIHandler)
    set_server_url(f"http://{host}:{port}")
    print(f"[webui] http://{host}:{port}/  (snapshots: {_SNAPSHOT_ROOT})")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n[webui] shutdown")
        server.shutdown()


if __name__ == "__main__":
    p = argparse.ArgumentParser(description="WorldsFinestVRP live web UI")
    p.add_argument("--port", type=int, default=8765)
    p.add_argument("--host", default="127.0.0.1")
    args = p.parse_args()
    serve(port=args.port, host=args.host)
